Class lscalese.configcopy.client.msg.ParsedResponse Extends (%Persistent, %XML.Adaptor) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="ParsedResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^lscalese.coD0BB.ParsedResponseD</DataLocation>
<DefaultData>ParsedResponseDefaultData</DefaultData>
<IdLocation>^lscalese.coD0BB.ParsedResponseD</IdLocation>
<IndexLocation>^lscalese.coD0BB.ParsedResponseI</IndexLocation>
<StreamLocation>^lscalese.coD0BB.ParsedResponseS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
